language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

notifications:
  email:
    on_success: always
    on_failure: always

install:
  - "pip install WebTest"

script: make test
